INSERT INTO products VALUES('1','Snack foods','28WxiNzY4u',37);
INSERT INTO products VALUES('2','Dishware','XnM1ZV82yQ',9);
INSERT INTO products VALUES('3','Bread','0Dl103F4Qv',6);
INSERT INTO products VALUES('4','Baby food','9whWD0GVco',4);
INSERT INTO products VALUES('5','Cereals','gJibhWHlxn',47);
INSERT INTO products VALUES('6','Cosmetics','m8hBozJmgA',43);
INSERT INTO products VALUES('7','Flour','xmy7JzQL9j',17);
INSERT INTO products VALUES('8','Housewares','UoX4nfYWzC',37);
INSERT INTO products VALUES('9','White rice','TFqnfbffS6',32);
INSERT INTO products VALUES('10','Nonalcoholic beverages','iKb8WwfCn1',35);
INSERT INTO products VALUES('11','Canned Goods','bP8Bmexu2t',32);
INSERT INTO products VALUES('12','White rice','InphEzXYAc',18);
INSERT INTO products VALUES('13','Pet foods','EZAChqbcXq',9);
INSERT INTO products VALUES('14','Dry Goods','dd3xI2CygW',41);
INSERT INTO products VALUES('15','Candies','G88ydT993f',47);
INSERT INTO products VALUES('16','Olive oil','euNLSMrccY',4);
INSERT INTO products VALUES('17','Bakery products','5jPIZh7rkR',46);
INSERT INTO products VALUES('18','Hygiene products','sm8EqLX7gr',16);
INSERT INTO products VALUES('19','Flowers','p1gUpXPr4Y',44);
INSERT INTO products VALUES('20','Coffee','D1kVhPmMyo',23);
INSERT INTO products VALUES('21','Decorations','NmvRBGENQ1',23);
INSERT INTO products VALUES('22','Dairy','AnCMCOpUtF',1);
INSERT INTO products VALUES('23','House-cleaning products','lBaQFGkBY1',6);
INSERT INTO products VALUES('24','Grooming products','m8qxUpnMXC',17);
INSERT INTO products VALUES('25','Nonalcoholic beverages','NZKj8I5Hl5',34);
INSERT INTO products VALUES('26','Canned Goods','pxIJQbJJg9',29);
INSERT INTO products VALUES('27','Medicines','i1AEcybiqg',3);
INSERT INTO products VALUES('28','Decorations','6ACP58arRp',7);
INSERT INTO products VALUES('29','Seafood','gd563LXN0G',2);
INSERT INTO products VALUES('30','Mustard','I1pxdHUJud',11);
INSERT INTO products VALUES('31','Meat','Z3Nhi2w2td',27);
INSERT INTO products VALUES('32','Frozen foods','2foeIzz084',6);
INSERT INTO products VALUES('33','Medicines','TnNJV8vDQp',26);
INSERT INTO products VALUES('34','Canned Goods','7zp7TJYpUq',46);
INSERT INTO products VALUES('35','Ground turkey','czB5oWRfvJ',12);
INSERT INTO products VALUES('36','Snack foods','pmgurdsM9o',27);
INSERT INTO products VALUES('37','Fish','J1gygcumsP',34);
INSERT INTO products VALUES('38','Seafood','70Z3XBOylt',15);
INSERT INTO products VALUES('39','Housewares','mn708s8ySs',38);
INSERT INTO products VALUES('40','Bottled waters','zc8TYlNZ6B',40);
INSERT INTO products VALUES('41','Chicken','Eyy7Zsraj0',10);
INSERT INTO products VALUES('42','Personal Care','e4o9R2NPEn',4);
INSERT INTO products VALUES('43','Nonalcoholic beverages','C5Z9g3ul0G',39);
INSERT INTO products VALUES('44','Detergents','3AYkAVM9QG',41);
INSERT INTO products VALUES('45','Cosmetics','7NHDyiwau3',46);
INSERT INTO products VALUES('46','Cosmetics','Sr3qFkBYHe',5);
INSERT INTO products VALUES('47','Dry Goods','emOtaEo5G4',3);
INSERT INTO products VALUES('48','Fish','vqxSTVYAF3',14);
INSERT INTO products VALUES('49','Fish','bg3qEZXcI0',29);
INSERT INTO products VALUES('50','Baby food','TD9qP9YXok',46);
INSERT INTO products VALUES('51','Tomato sauce','xtFvFFLkV5',14);
INSERT INTO products VALUES('52','Nonalcoholic beverages','K81qhkK4Hl',49);
INSERT INTO products VALUES('53','Dry Goods','VsuFe3n1le',44);
INSERT INTO products VALUES('54','Fruits','UlWCo80XvF',26);
INSERT INTO products VALUES('55','Dry Goods','IszEaARLuy',21);
INSERT INTO products VALUES('56','Pasta','UGGbSaTpFg',17);
INSERT INTO products VALUES('57','Vegetables','OHPIvlfQMd',47);
INSERT INTO products VALUES('58','Bottled waters','DjbkNrkgL8',36);
INSERT INTO products VALUES('59','Alcoholic beverages','2YFVw0LmW3',42);
INSERT INTO products VALUES('60','Personal hygiene','uIZJTJK0JT',19);
INSERT INTO products VALUES('61','Bread','8sbY6yvPZr',13);
INSERT INTO products VALUES('62','Pasta','fJeVSVZKtI',42);
INSERT INTO products VALUES('63','Medicines','RaNBx1ZiBW',18);
INSERT INTO products VALUES('64','Medicines','YxphIk3D2C',32);
INSERT INTO products VALUES('65','Detergents','pzix4N902X',6);
INSERT INTO products VALUES('66','Seafood','ltbhRrVJwa',47);
INSERT INTO products VALUES('67','Cosmetics','p1CIOwLOwD',19);
INSERT INTO products VALUES('68','Ground turkey','SloxXgMBqK',47);
INSERT INTO products VALUES('69','Tomato sauce','JWwLreWP2E',7);
INSERT INTO products VALUES('70','Grooming products','L0lFL1tiWc',12);
INSERT INTO products VALUES('71','Housewares','ChvQO5xf5n',49);
INSERT INTO products VALUES('72','Personal Care','AAhRqHGOcm',31);
INSERT INTO products VALUES('73','Seafood','4GzyaYCrHF',8);
INSERT INTO products VALUES('74','Detergents','tGA6QnHh1s',5);
INSERT INTO products VALUES('75','Baby food','Ub1OV9Na4P',18);
INSERT INTO products VALUES('76','Mustard','G8EgkRv40X',28);
INSERT INTO products VALUES('77','Bakery products','GK8zfEoLAo',25);
INSERT INTO products VALUES('78','Ground turkey','gyVH2tOet3',42);
INSERT INTO products VALUES('79','Personal hygiene','ik7j7KU63R',6);
INSERT INTO products VALUES('80','Baby food','BX50kKGbeG',1);
INSERT INTO products VALUES('81','Bottled waters','6nBHIE0NTq',14);
INSERT INTO products VALUES('82','Nonalcoholic beverages','HEOzThFPqJ',5);
INSERT INTO products VALUES('83','Cosmetics','yY3jwYxckK',31);
INSERT INTO products VALUES('84','Fruits','JMxza31VGA',36);
INSERT INTO products VALUES('85','Cosmetics','6QI6AuFxhg',16);
INSERT INTO products VALUES('86','Condiments','KQb53yU6b4',34);
INSERT INTO products VALUES('87','Mustard','tPywRuYxqY',32);
INSERT INTO products VALUES('88','Cosmetics','Q0bzFzwm2D',33);
INSERT INTO products VALUES('89','Detergents','c6cSpwDCkA',11);
INSERT INTO products VALUES('90','Baby-care','5SfwIgEvn5',33);
INSERT INTO products VALUES('91','Cereals','We1mHEOqko',17);
INSERT INTO products VALUES('92','Brown rice','SFI3Ul5Pnq',45);
INSERT INTO products VALUES('93','Bottled waters','UAdW93ggQZ',46);
INSERT INTO products VALUES('94','Baby food','4b4fwgKR8J',24);
INSERT INTO products VALUES('95','Grooming products','YKbCAZYqkF',15);
INSERT INTO products VALUES('96','Mustard','l1qrHxE2K7',49);
INSERT INTO products VALUES('97','Coffee','qZdHfmxKga',48);
INSERT INTO products VALUES('98','Sweets','ceg1BPkzJx',45);
INSERT INTO products VALUES('99','Nonalcoholic beverages','0dJLEl2aLh',18);
INSERT INTO products VALUES('100','Bakery products','6RK7RIkK31',12);